### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-laila25#1]
Really cool job @laila25 !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Should the `.menu` element be a nonsemantics `div` or a rich semantic `nav` (commonly used for our main navigation)
- [x] Use ul and li in menu.

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - box model
- [x] Block elements like our main one do not need a width: 100% or width: 100vw property to tell them to do what they are going to do anyway ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)
- [x] Header should be fixed to top of the page.

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Do not repeat css properties in media queries like https://github.com/Adalab/m1-evaluacion-intermedia-laila25/blob/master/styles/main.css#L60

## Good practices
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

## Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Casi perfecto @laila25, podemos estar muy contentos!!!

![Good job](https://media.giphy.com/media/1ncs69mepw2hbyxIj1/giphy.gif)

**Comment by laila25** [comment]
hola
ya he realizado los cambios y he ido comiteandolos por las secciones que has puesto.

Solo tengo la duda de: "Move the font CSS before your main CSS"
no se a que te refieres

**Comment by migueldelmazo** [comment]
Eso quería decir que la importación del css de fuentes tiene que ir antes que la importación de tu propio css. He visto que ahora está bien en tu HTML, así que supongo que se me piró. 

Buen trabajo!!

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
